name: 构建打包
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: echo (node -p -e '`VERSION=${require("./package.json").version}`') >> $Env:GITHUB_ENV
      - run: npm install
      - run: npm run package
      - uses: maotoumao/inno-setup-action-cli@main
        with:
          filepath: ./release/build-windows.iss
          variables: /DMyAppVersion=${{ env.VERSION }} /DMyAppId=${{ secrets.MYAPPID }}
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: MusicFreeSetup-windows.exe
          path: ./out/MusicFreeSetup.exe
      - name: Generate Portable
        run: mkdir ./out/MusicFree-win32-x64/portable
      - uses: vimtor/action-zip@v1.1
        with:
          files: ./out/MusicFree-win32-x64
          dest: ./out/MusicFree-win32-x64.zip
      - name: Upload Portable
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-win32-x64.zip
          path: ./out/MusicFree-win32-x64.zip

  build-windows-legacy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: echo (node -p -e '`VERSION=${require("./package.json").version}`') >> $Env:GITHUB_ENV
      - run: npm install
      - run: npm install electron@22
      - run: npm run package
      - uses: maotoumao/inno-setup-action-cli@main
        with:
          filepath: ./release/build-windows.iss
          variables: /DMyAppVersion=${{ env.VERSION }} /DMyAppId=${{ secrets.MYAPPID }}
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: MusicFreeSetup-windows-legacy.exe
          path: ./out/MusicFreeSetup.exe
      - name: Generate Portable
        run: mkdir ./out/MusicFree-win32-x64/portable
      - uses: vimtor/action-zip@v1.1
        with:
          files: ./out/MusicFree-win32-x64
          dest: ./out/MusicFree-win32-x64-legacy.zip
      - name: Upload Portable
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-win32-x64-legacy.zip
          path: ./out/MusicFree-win32-x64-legacy.zip

  build-macos-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - run: npm install
      - run: npm run make
      - run: ls ./out/make
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-macos-x64.dmg
          path: ./out/make/MusicFree-${{ env.VERSION }}-x64.dmg

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - run: npm install
      - run: npm run make -- --arch="arm64"
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-macos-arm64.dmg
          path: ./out/make/MusicFree-${{ env.VERSION }}-arm64.dmg

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - run: npm install
      - run: npm run make
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-ubuntu
          path: ./out/make/deb/x64/

  release:
    needs: [build-windows, build-windows-legacy, build-macos-x64, build-macos-arm64, build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create Release Tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git fetch --prune --unshallow
          git tag v${VERSION}
          git push origin v${VERSION}
      - uses: actions/download-artifact@v4
        with:
          name: MusicFreeSetup-windows.exe
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFree-win32-x64.zip
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFreeSetup-windows-legacy.exe
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFree-win32-x64-legacy.zip
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFree-macos-x64.dmg
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFree-macos-arm64.dmg
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: MusicFree-ubuntu
          path: ./artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
